org: danipoav
app: api
service: api

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-3
  stage: dev
  environment:
    NODE_ENV: ${opt:stage, 'dev'}  

functions:
  api:
    handler: app.handler  
    events:
      - httpApi: "*"  

