org: danipoav
app: api
service: api

provider:
  name: aws
  runtime: nodejs22.x
  region: eu-west-3
  stage: dev
  environment:
    SECRET_KEY: ${env:SECRET_KEY}
    ATLAS_PASSWORD: ${env:ATLAS_PASSWORD}
    ATLAS_USER: ${env:ATLAS_USER}

functions:
  api:
    handler: src/app.handler
    events:
      - httpApi: "*"
      
package:
  exclude:
    - node_modules/@mapbox/node-pre-gyp/lib/util/nw-pre-gyp/index.html
    - node_modules/@mapbox/node-pre-gyp/lib/util/*.html